### ISSUE TITLE
Nested JSON Objects seem to fail

### ISSUE THREAD

**Issue by vortex314** [lusoalex/vertx-jolt#1]

**Comment by vortex314** [comment]
I suspect that the JSonUtils from JOLT itself created their own internal Jackson based objects incompatible with Vertx JsonObjects ?

**Comment by vortex314** [comment]
Now it looks like this and works with the original Jolt 
JsonObject out = new JsonObject(JsonUtils.toJsonString(chainedRules.transform(JsonUtils.jsonToObject(in.encode()))));
Ugly, I know.

**Comment by lusoalex** [comment]
Hello,
Sorry for the delay, could you do a PR with your test case?
That way i'll work on a clean solution ;)
Thanks!
